version: "3"

networks:
  my-network:
    driver: bridge

services:
  # MySql container
  mysql:
    container_name: mysql-ctn
    hostname: mysql
    image: "mysql:latest"
    volumes:
      # init database
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - my-network
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shopee_clone_db
  # Spring boot app container
  app:
    container_name: my-app
    hostname: java-spring
    build:
      dockerfile: Dockerfile
      context: ./
    expose:
      - 8080
    networks:
      - my-network
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: mysql-ctn
      MYSQL_PORT: 3307
      MYSQL_DB_NAME: shopee_clone_db
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root

